// flow-typed signature: 41bbbd7d6eedb676c058057ff4f0e2ff
// flow-typed version: <<STUB>>/react-dom_v15.5.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dom/dist/react-dom-server' {
  declare module.exports: any;
}

declare module 'react-dom/dist/react-dom-server.min' {
  declare module.exports: any;
}

declare module 'react-dom/dist/react-dom' {
  declare module.exports: any;
}

declare module 'react-dom/dist/react-dom.min' {
  declare module.exports: any;
}

declare module 'react-dom/lib/accumulate' {
  declare module.exports: any;
}

declare module 'react-dom/lib/accumulateInto' {
  declare module.exports: any;
}

declare module 'react-dom/lib/adler32' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ARIADOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'react-dom/lib/AutoFocusUtils' {
  declare module.exports: any;
}

declare module 'react-dom/lib/BeforeInputEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom/lib/CallbackQueue' {
  declare module.exports: any;
}

declare module 'react-dom/lib/canDefineProperty' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ChangeEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom/lib/checkReactTypeSpec' {
  declare module.exports: any;
}

declare module 'react-dom/lib/createMicrosoftUnsafeLocalFunction' {
  declare module.exports: any;
}

declare module 'react-dom/lib/CSSProperty' {
  declare module.exports: any;
}

declare module 'react-dom/lib/CSSPropertyOperations' {
  declare module.exports: any;
}

declare module 'react-dom/lib/Danger' {
  declare module.exports: any;
}

declare module 'react-dom/lib/dangerousStyleValue' {
  declare module.exports: any;
}

declare module 'react-dom/lib/DefaultEventPluginOrder' {
  declare module.exports: any;
}

declare module 'react-dom/lib/deprecated' {
  declare module.exports: any;
}

declare module 'react-dom/lib/DOMChildrenOperations' {
  declare module.exports: any;
}

declare module 'react-dom/lib/DOMLazyTree' {
  declare module.exports: any;
}

declare module 'react-dom/lib/DOMNamespaces' {
  declare module.exports: any;
}

declare module 'react-dom/lib/DOMProperty' {
  declare module.exports: any;
}

declare module 'react-dom/lib/DOMPropertyOperations' {
  declare module.exports: any;
}

declare module 'react-dom/lib/EnterLeaveEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom/lib/escapeTextContentForBrowser' {
  declare module.exports: any;
}

declare module 'react-dom/lib/EventConstants' {
  declare module.exports: any;
}

declare module 'react-dom/lib/EventPluginHub' {
  declare module.exports: any;
}

declare module 'react-dom/lib/EventPluginRegistry' {
  declare module.exports: any;
}

declare module 'react-dom/lib/EventPluginUtils' {
  declare module.exports: any;
}

declare module 'react-dom/lib/EventPropagators' {
  declare module.exports: any;
}

declare module 'react-dom/lib/FallbackCompositionState' {
  declare module.exports: any;
}

declare module 'react-dom/lib/findDOMNode' {
  declare module.exports: any;
}

declare module 'react-dom/lib/flattenChildren' {
  declare module.exports: any;
}

declare module 'react-dom/lib/forEachAccumulated' {
  declare module.exports: any;
}

declare module 'react-dom/lib/getEventCharCode' {
  declare module.exports: any;
}

declare module 'react-dom/lib/getEventKey' {
  declare module.exports: any;
}

declare module 'react-dom/lib/getEventModifierState' {
  declare module.exports: any;
}

declare module 'react-dom/lib/getEventTarget' {
  declare module.exports: any;
}

declare module 'react-dom/lib/getHostComponentFromComposite' {
  declare module.exports: any;
}

declare module 'react-dom/lib/getIteratorFn' {
  declare module.exports: any;
}

declare module 'react-dom/lib/getNodeForCharacterOffset' {
  declare module.exports: any;
}

declare module 'react-dom/lib/getTestDocument' {
  declare module.exports: any;
}

declare module 'react-dom/lib/getTextContentAccessor' {
  declare module.exports: any;
}

declare module 'react-dom/lib/getVendorPrefixedEventName' {
  declare module.exports: any;
}

declare module 'react-dom/lib/HTMLDOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'react-dom/lib/instantiateReactComponent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/isEventSupported' {
  declare module.exports: any;
}

declare module 'react-dom/lib/isTextInputElement' {
  declare module.exports: any;
}

declare module 'react-dom/lib/KeyEscapeUtils' {
  declare module.exports: any;
}

declare module 'react-dom/lib/LinkedValueUtils' {
  declare module.exports: any;
}

declare module 'react-dom/lib/PluginModuleType' {
  declare module.exports: any;
}

declare module 'react-dom/lib/PooledClass' {
  declare module.exports: any;
}

declare module 'react-dom/lib/quoteAttributeValueForBrowser' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactBrowserEventEmitter' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactChildFiber' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactChildReconciler' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactComponentBrowserEnvironment' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactComponentEnvironment' {
  declare module.exports: any;
}

declare module 'react-dom/lib/reactComponentExpect' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactComponentTreeTestUtils' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactCompositeComponent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactCoroutine' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDebugTool' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDefaultBatchingStrategy' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDefaultInjection' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOM' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMComponent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMComponentFlags' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMComponentTree' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMContainerInfo' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMFeatureFlags' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMFiber' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMIDOperations' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMInput' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMInvalidARIAHook' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMNullInputValuePropHook' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMOption' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMSelect' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMSelection' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMServer' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMServerUMDEntry' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMTextarea' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMTextComponent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMTreeTraversal' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMUMDEntry' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactDOMUnknownPropertyHook' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactElementSymbol' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactErrorUtils' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactEventEmitterMixin' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactEventListener' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactFeatureFlags' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactFiber' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactFiberBeginWork' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactFiberCommitWork' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactFiberCompleteWork' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactFiberReconciler' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactFiberRoot' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactFiberScheduler' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactFiberUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactHostComponent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactHostOperationHistoryHook' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactInjection' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactInputSelection' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactInstanceMap' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactInstanceType' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactInstrumentation' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactInvalidSetStateWarningHook' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactMarkupChecksum' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactMount' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactMultiChild' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactMultiChildUpdateTypes' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactNodeTypes' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactOwner' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactPerf' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactPriorityLevel' {
  declare module.exports: any;
}

declare module 'react-dom/lib/reactProdInvariant' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactPropTypeLocationNames' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactPropTypeLocations' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactPropTypesSecret' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactReconciler' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactReconcileTransaction' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactRef' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactReifiedYield' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactServerBatchingStrategy' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactServerRendering' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactServerRenderingTransaction' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactServerUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactShallowRenderer' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactSimpleEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactSyntheticEventType' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactTestReconcileTransaction' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactTestUtils' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactTypeOfWork' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactTypes' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactUpdates' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ReactVersion' {
  declare module.exports: any;
}

declare module 'react-dom/lib/renderSubtreeIntoContainer' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ResponderSyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ResponderTouchHistoryStore' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SelectEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom/lib/setInnerHTML' {
  declare module.exports: any;
}

declare module 'react-dom/lib/setTextContent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/shouldUpdateReactComponent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SimpleEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SVGDOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticAnimationEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticClipboardEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticCompositionEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticDragEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticFocusEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticInputEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticKeyboardEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticMouseEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticTouchEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticTransitionEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticUIEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/SyntheticWheelEvent' {
  declare module.exports: any;
}

declare module 'react-dom/lib/TapEventPlugin' {
  declare module.exports: any;
}

declare module 'react-dom/lib/TouchHistoryMath' {
  declare module.exports: any;
}

declare module 'react-dom/lib/Transaction' {
  declare module.exports: any;
}

declare module 'react-dom/lib/traverseAllChildren' {
  declare module.exports: any;
}

declare module 'react-dom/lib/validateDOMNesting' {
  declare module.exports: any;
}

declare module 'react-dom/lib/ViewportMetrics' {
  declare module.exports: any;
}

declare module 'react-dom/server' {
  declare module.exports: any;
}

declare module 'react-dom/test-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dom/dist/react-dom-server.js' {
  declare module.exports: $Exports<'react-dom/dist/react-dom-server'>;
}
declare module 'react-dom/dist/react-dom-server.min.js' {
  declare module.exports: $Exports<'react-dom/dist/react-dom-server.min'>;
}
declare module 'react-dom/dist/react-dom.js' {
  declare module.exports: $Exports<'react-dom/dist/react-dom'>;
}
declare module 'react-dom/dist/react-dom.min.js' {
  declare module.exports: $Exports<'react-dom/dist/react-dom.min'>;
}
declare module 'react-dom/index' {
  declare module.exports: $Exports<'react-dom'>;
}
declare module 'react-dom/index.js' {
  declare module.exports: $Exports<'react-dom'>;
}
declare module 'react-dom/lib/accumulate.js' {
  declare module.exports: $Exports<'react-dom/lib/accumulate'>;
}
declare module 'react-dom/lib/accumulateInto.js' {
  declare module.exports: $Exports<'react-dom/lib/accumulateInto'>;
}
declare module 'react-dom/lib/adler32.js' {
  declare module.exports: $Exports<'react-dom/lib/adler32'>;
}
declare module 'react-dom/lib/ARIADOMPropertyConfig.js' {
  declare module.exports: $Exports<'react-dom/lib/ARIADOMPropertyConfig'>;
}
declare module 'react-dom/lib/AutoFocusUtils.js' {
  declare module.exports: $Exports<'react-dom/lib/AutoFocusUtils'>;
}
declare module 'react-dom/lib/BeforeInputEventPlugin.js' {
  declare module.exports: $Exports<'react-dom/lib/BeforeInputEventPlugin'>;
}
declare module 'react-dom/lib/CallbackQueue.js' {
  declare module.exports: $Exports<'react-dom/lib/CallbackQueue'>;
}
declare module 'react-dom/lib/canDefineProperty.js' {
  declare module.exports: $Exports<'react-dom/lib/canDefineProperty'>;
}
declare module 'react-dom/lib/ChangeEventPlugin.js' {
  declare module.exports: $Exports<'react-dom/lib/ChangeEventPlugin'>;
}
declare module 'react-dom/lib/checkReactTypeSpec.js' {
  declare module.exports: $Exports<'react-dom/lib/checkReactTypeSpec'>;
}
declare module 'react-dom/lib/createMicrosoftUnsafeLocalFunction.js' {
  declare module.exports: $Exports<'react-dom/lib/createMicrosoftUnsafeLocalFunction'>;
}
declare module 'react-dom/lib/CSSProperty.js' {
  declare module.exports: $Exports<'react-dom/lib/CSSProperty'>;
}
declare module 'react-dom/lib/CSSPropertyOperations.js' {
  declare module.exports: $Exports<'react-dom/lib/CSSPropertyOperations'>;
}
declare module 'react-dom/lib/Danger.js' {
  declare module.exports: $Exports<'react-dom/lib/Danger'>;
}
declare module 'react-dom/lib/dangerousStyleValue.js' {
  declare module.exports: $Exports<'react-dom/lib/dangerousStyleValue'>;
}
declare module 'react-dom/lib/DefaultEventPluginOrder.js' {
  declare module.exports: $Exports<'react-dom/lib/DefaultEventPluginOrder'>;
}
declare module 'react-dom/lib/deprecated.js' {
  declare module.exports: $Exports<'react-dom/lib/deprecated'>;
}
declare module 'react-dom/lib/DOMChildrenOperations.js' {
  declare module.exports: $Exports<'react-dom/lib/DOMChildrenOperations'>;
}
declare module 'react-dom/lib/DOMLazyTree.js' {
  declare module.exports: $Exports<'react-dom/lib/DOMLazyTree'>;
}
declare module 'react-dom/lib/DOMNamespaces.js' {
  declare module.exports: $Exports<'react-dom/lib/DOMNamespaces'>;
}
declare module 'react-dom/lib/DOMProperty.js' {
  declare module.exports: $Exports<'react-dom/lib/DOMProperty'>;
}
declare module 'react-dom/lib/DOMPropertyOperations.js' {
  declare module.exports: $Exports<'react-dom/lib/DOMPropertyOperations'>;
}
declare module 'react-dom/lib/EnterLeaveEventPlugin.js' {
  declare module.exports: $Exports<'react-dom/lib/EnterLeaveEventPlugin'>;
}
declare module 'react-dom/lib/escapeTextContentForBrowser.js' {
  declare module.exports: $Exports<'react-dom/lib/escapeTextContentForBrowser'>;
}
declare module 'react-dom/lib/EventConstants.js' {
  declare module.exports: $Exports<'react-dom/lib/EventConstants'>;
}
declare module 'react-dom/lib/EventPluginHub.js' {
  declare module.exports: $Exports<'react-dom/lib/EventPluginHub'>;
}
declare module 'react-dom/lib/EventPluginRegistry.js' {
  declare module.exports: $Exports<'react-dom/lib/EventPluginRegistry'>;
}
declare module 'react-dom/lib/EventPluginUtils.js' {
  declare module.exports: $Exports<'react-dom/lib/EventPluginUtils'>;
}
declare module 'react-dom/lib/EventPropagators.js' {
  declare module.exports: $Exports<'react-dom/lib/EventPropagators'>;
}
declare module 'react-dom/lib/FallbackCompositionState.js' {
  declare module.exports: $Exports<'react-dom/lib/FallbackCompositionState'>;
}
declare module 'react-dom/lib/findDOMNode.js' {
  declare module.exports: $Exports<'react-dom/lib/findDOMNode'>;
}
declare module 'react-dom/lib/flattenChildren.js' {
  declare module.exports: $Exports<'react-dom/lib/flattenChildren'>;
}
declare module 'react-dom/lib/forEachAccumulated.js' {
  declare module.exports: $Exports<'react-dom/lib/forEachAccumulated'>;
}
declare module 'react-dom/lib/getEventCharCode.js' {
  declare module.exports: $Exports<'react-dom/lib/getEventCharCode'>;
}
declare module 'react-dom/lib/getEventKey.js' {
  declare module.exports: $Exports<'react-dom/lib/getEventKey'>;
}
declare module 'react-dom/lib/getEventModifierState.js' {
  declare module.exports: $Exports<'react-dom/lib/getEventModifierState'>;
}
declare module 'react-dom/lib/getEventTarget.js' {
  declare module.exports: $Exports<'react-dom/lib/getEventTarget'>;
}
declare module 'react-dom/lib/getHostComponentFromComposite.js' {
  declare module.exports: $Exports<'react-dom/lib/getHostComponentFromComposite'>;
}
declare module 'react-dom/lib/getIteratorFn.js' {
  declare module.exports: $Exports<'react-dom/lib/getIteratorFn'>;
}
declare module 'react-dom/lib/getNodeForCharacterOffset.js' {
  declare module.exports: $Exports<'react-dom/lib/getNodeForCharacterOffset'>;
}
declare module 'react-dom/lib/getTestDocument.js' {
  declare module.exports: $Exports<'react-dom/lib/getTestDocument'>;
}
declare module 'react-dom/lib/getTextContentAccessor.js' {
  declare module.exports: $Exports<'react-dom/lib/getTextContentAccessor'>;
}
declare module 'react-dom/lib/getVendorPrefixedEventName.js' {
  declare module.exports: $Exports<'react-dom/lib/getVendorPrefixedEventName'>;
}
declare module 'react-dom/lib/HTMLDOMPropertyConfig.js' {
  declare module.exports: $Exports<'react-dom/lib/HTMLDOMPropertyConfig'>;
}
declare module 'react-dom/lib/instantiateReactComponent.js' {
  declare module.exports: $Exports<'react-dom/lib/instantiateReactComponent'>;
}
declare module 'react-dom/lib/isEventSupported.js' {
  declare module.exports: $Exports<'react-dom/lib/isEventSupported'>;
}
declare module 'react-dom/lib/isTextInputElement.js' {
  declare module.exports: $Exports<'react-dom/lib/isTextInputElement'>;
}
declare module 'react-dom/lib/KeyEscapeUtils.js' {
  declare module.exports: $Exports<'react-dom/lib/KeyEscapeUtils'>;
}
declare module 'react-dom/lib/LinkedValueUtils.js' {
  declare module.exports: $Exports<'react-dom/lib/LinkedValueUtils'>;
}
declare module 'react-dom/lib/PluginModuleType.js' {
  declare module.exports: $Exports<'react-dom/lib/PluginModuleType'>;
}
declare module 'react-dom/lib/PooledClass.js' {
  declare module.exports: $Exports<'react-dom/lib/PooledClass'>;
}
declare module 'react-dom/lib/quoteAttributeValueForBrowser.js' {
  declare module.exports: $Exports<'react-dom/lib/quoteAttributeValueForBrowser'>;
}
declare module 'react-dom/lib/ReactBrowserEventEmitter.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactBrowserEventEmitter'>;
}
declare module 'react-dom/lib/ReactChildFiber.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactChildFiber'>;
}
declare module 'react-dom/lib/ReactChildReconciler.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactChildReconciler'>;
}
declare module 'react-dom/lib/ReactComponentBrowserEnvironment.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactComponentBrowserEnvironment'>;
}
declare module 'react-dom/lib/ReactComponentEnvironment.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactComponentEnvironment'>;
}
declare module 'react-dom/lib/reactComponentExpect.js' {
  declare module.exports: $Exports<'react-dom/lib/reactComponentExpect'>;
}
declare module 'react-dom/lib/ReactComponentTreeTestUtils.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactComponentTreeTestUtils'>;
}
declare module 'react-dom/lib/ReactCompositeComponent.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactCompositeComponent'>;
}
declare module 'react-dom/lib/ReactCoroutine.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactCoroutine'>;
}
declare module 'react-dom/lib/ReactDebugTool.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDebugTool'>;
}
declare module 'react-dom/lib/ReactDefaultBatchingStrategy.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDefaultBatchingStrategy'>;
}
declare module 'react-dom/lib/ReactDefaultInjection.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDefaultInjection'>;
}
declare module 'react-dom/lib/ReactDOM.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOM'>;
}
declare module 'react-dom/lib/ReactDOMComponent.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMComponent'>;
}
declare module 'react-dom/lib/ReactDOMComponentFlags.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMComponentFlags'>;
}
declare module 'react-dom/lib/ReactDOMComponentTree.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMComponentTree'>;
}
declare module 'react-dom/lib/ReactDOMContainerInfo.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMContainerInfo'>;
}
declare module 'react-dom/lib/ReactDOMEmptyComponent.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMEmptyComponent'>;
}
declare module 'react-dom/lib/ReactDOMFeatureFlags.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMFeatureFlags'>;
}
declare module 'react-dom/lib/ReactDOMFiber.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMFiber'>;
}
declare module 'react-dom/lib/ReactDOMIDOperations.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMIDOperations'>;
}
declare module 'react-dom/lib/ReactDOMInput.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMInput'>;
}
declare module 'react-dom/lib/ReactDOMInvalidARIAHook.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMInvalidARIAHook'>;
}
declare module 'react-dom/lib/ReactDOMNullInputValuePropHook.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMNullInputValuePropHook'>;
}
declare module 'react-dom/lib/ReactDOMOption.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMOption'>;
}
declare module 'react-dom/lib/ReactDOMSelect.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMSelect'>;
}
declare module 'react-dom/lib/ReactDOMSelection.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMSelection'>;
}
declare module 'react-dom/lib/ReactDOMServer.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMServer'>;
}
declare module 'react-dom/lib/ReactDOMServerUMDEntry.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMServerUMDEntry'>;
}
declare module 'react-dom/lib/ReactDOMTextarea.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMTextarea'>;
}
declare module 'react-dom/lib/ReactDOMTextComponent.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMTextComponent'>;
}
declare module 'react-dom/lib/ReactDOMTreeTraversal.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMTreeTraversal'>;
}
declare module 'react-dom/lib/ReactDOMUMDEntry.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMUMDEntry'>;
}
declare module 'react-dom/lib/ReactDOMUnknownPropertyHook.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactDOMUnknownPropertyHook'>;
}
declare module 'react-dom/lib/ReactElementSymbol.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactElementSymbol'>;
}
declare module 'react-dom/lib/ReactEmptyComponent.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactEmptyComponent'>;
}
declare module 'react-dom/lib/ReactErrorUtils.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactErrorUtils'>;
}
declare module 'react-dom/lib/ReactEventEmitterMixin.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactEventEmitterMixin'>;
}
declare module 'react-dom/lib/ReactEventListener.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactEventListener'>;
}
declare module 'react-dom/lib/ReactFeatureFlags.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactFeatureFlags'>;
}
declare module 'react-dom/lib/ReactFiber.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactFiber'>;
}
declare module 'react-dom/lib/ReactFiberBeginWork.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactFiberBeginWork'>;
}
declare module 'react-dom/lib/ReactFiberCommitWork.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactFiberCommitWork'>;
}
declare module 'react-dom/lib/ReactFiberCompleteWork.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactFiberCompleteWork'>;
}
declare module 'react-dom/lib/ReactFiberReconciler.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactFiberReconciler'>;
}
declare module 'react-dom/lib/ReactFiberRoot.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactFiberRoot'>;
}
declare module 'react-dom/lib/ReactFiberScheduler.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactFiberScheduler'>;
}
declare module 'react-dom/lib/ReactFiberUpdateQueue.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactFiberUpdateQueue'>;
}
declare module 'react-dom/lib/ReactHostComponent.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactHostComponent'>;
}
declare module 'react-dom/lib/ReactHostOperationHistoryHook.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactHostOperationHistoryHook'>;
}
declare module 'react-dom/lib/ReactInjection.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactInjection'>;
}
declare module 'react-dom/lib/ReactInputSelection.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactInputSelection'>;
}
declare module 'react-dom/lib/ReactInstanceMap.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactInstanceMap'>;
}
declare module 'react-dom/lib/ReactInstanceType.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactInstanceType'>;
}
declare module 'react-dom/lib/ReactInstrumentation.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactInstrumentation'>;
}
declare module 'react-dom/lib/ReactInvalidSetStateWarningHook.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactInvalidSetStateWarningHook'>;
}
declare module 'react-dom/lib/ReactMarkupChecksum.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactMarkupChecksum'>;
}
declare module 'react-dom/lib/ReactMount.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactMount'>;
}
declare module 'react-dom/lib/ReactMultiChild.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactMultiChild'>;
}
declare module 'react-dom/lib/ReactMultiChildUpdateTypes.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactMultiChildUpdateTypes'>;
}
declare module 'react-dom/lib/ReactNodeTypes.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactNodeTypes'>;
}
declare module 'react-dom/lib/ReactOwner.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactOwner'>;
}
declare module 'react-dom/lib/ReactPerf.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactPerf'>;
}
declare module 'react-dom/lib/ReactPriorityLevel.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactPriorityLevel'>;
}
declare module 'react-dom/lib/reactProdInvariant.js' {
  declare module.exports: $Exports<'react-dom/lib/reactProdInvariant'>;
}
declare module 'react-dom/lib/ReactPropTypeLocationNames.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactPropTypeLocationNames'>;
}
declare module 'react-dom/lib/ReactPropTypeLocations.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactPropTypeLocations'>;
}
declare module 'react-dom/lib/ReactPropTypesSecret.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactPropTypesSecret'>;
}
declare module 'react-dom/lib/ReactReconciler.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactReconciler'>;
}
declare module 'react-dom/lib/ReactReconcileTransaction.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactReconcileTransaction'>;
}
declare module 'react-dom/lib/ReactRef.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactRef'>;
}
declare module 'react-dom/lib/ReactReifiedYield.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactReifiedYield'>;
}
declare module 'react-dom/lib/ReactServerBatchingStrategy.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactServerBatchingStrategy'>;
}
declare module 'react-dom/lib/ReactServerRendering.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactServerRendering'>;
}
declare module 'react-dom/lib/ReactServerRenderingTransaction.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactServerRenderingTransaction'>;
}
declare module 'react-dom/lib/ReactServerUpdateQueue.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactServerUpdateQueue'>;
}
declare module 'react-dom/lib/ReactShallowRenderer.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactShallowRenderer'>;
}
declare module 'react-dom/lib/ReactSimpleEmptyComponent.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactSimpleEmptyComponent'>;
}
declare module 'react-dom/lib/ReactSyntheticEventType.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactSyntheticEventType'>;
}
declare module 'react-dom/lib/ReactTestReconcileTransaction.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactTestReconcileTransaction'>;
}
declare module 'react-dom/lib/ReactTestUtils.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactTestUtils'>;
}
declare module 'react-dom/lib/ReactTypeOfWork.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactTypeOfWork'>;
}
declare module 'react-dom/lib/ReactTypes.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactTypes'>;
}
declare module 'react-dom/lib/ReactUpdateQueue.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactUpdateQueue'>;
}
declare module 'react-dom/lib/ReactUpdates.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactUpdates'>;
}
declare module 'react-dom/lib/ReactVersion.js' {
  declare module.exports: $Exports<'react-dom/lib/ReactVersion'>;
}
declare module 'react-dom/lib/renderSubtreeIntoContainer.js' {
  declare module.exports: $Exports<'react-dom/lib/renderSubtreeIntoContainer'>;
}
declare module 'react-dom/lib/ResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-dom/lib/ResponderEventPlugin'>;
}
declare module 'react-dom/lib/ResponderSyntheticEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/ResponderSyntheticEvent'>;
}
declare module 'react-dom/lib/ResponderTouchHistoryStore.js' {
  declare module.exports: $Exports<'react-dom/lib/ResponderTouchHistoryStore'>;
}
declare module 'react-dom/lib/SelectEventPlugin.js' {
  declare module.exports: $Exports<'react-dom/lib/SelectEventPlugin'>;
}
declare module 'react-dom/lib/setInnerHTML.js' {
  declare module.exports: $Exports<'react-dom/lib/setInnerHTML'>;
}
declare module 'react-dom/lib/setTextContent.js' {
  declare module.exports: $Exports<'react-dom/lib/setTextContent'>;
}
declare module 'react-dom/lib/shouldUpdateReactComponent.js' {
  declare module.exports: $Exports<'react-dom/lib/shouldUpdateReactComponent'>;
}
declare module 'react-dom/lib/SimpleEventPlugin.js' {
  declare module.exports: $Exports<'react-dom/lib/SimpleEventPlugin'>;
}
declare module 'react-dom/lib/SVGDOMPropertyConfig.js' {
  declare module.exports: $Exports<'react-dom/lib/SVGDOMPropertyConfig'>;
}
declare module 'react-dom/lib/SyntheticAnimationEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticAnimationEvent'>;
}
declare module 'react-dom/lib/SyntheticClipboardEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticClipboardEvent'>;
}
declare module 'react-dom/lib/SyntheticCompositionEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticCompositionEvent'>;
}
declare module 'react-dom/lib/SyntheticDragEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticDragEvent'>;
}
declare module 'react-dom/lib/SyntheticEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticEvent'>;
}
declare module 'react-dom/lib/SyntheticFocusEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticFocusEvent'>;
}
declare module 'react-dom/lib/SyntheticInputEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticInputEvent'>;
}
declare module 'react-dom/lib/SyntheticKeyboardEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticKeyboardEvent'>;
}
declare module 'react-dom/lib/SyntheticMouseEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticMouseEvent'>;
}
declare module 'react-dom/lib/SyntheticTouchEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticTouchEvent'>;
}
declare module 'react-dom/lib/SyntheticTransitionEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticTransitionEvent'>;
}
declare module 'react-dom/lib/SyntheticUIEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticUIEvent'>;
}
declare module 'react-dom/lib/SyntheticWheelEvent.js' {
  declare module.exports: $Exports<'react-dom/lib/SyntheticWheelEvent'>;
}
declare module 'react-dom/lib/TapEventPlugin.js' {
  declare module.exports: $Exports<'react-dom/lib/TapEventPlugin'>;
}
declare module 'react-dom/lib/TouchHistoryMath.js' {
  declare module.exports: $Exports<'react-dom/lib/TouchHistoryMath'>;
}
declare module 'react-dom/lib/Transaction.js' {
  declare module.exports: $Exports<'react-dom/lib/Transaction'>;
}
declare module 'react-dom/lib/traverseAllChildren.js' {
  declare module.exports: $Exports<'react-dom/lib/traverseAllChildren'>;
}
declare module 'react-dom/lib/validateDOMNesting.js' {
  declare module.exports: $Exports<'react-dom/lib/validateDOMNesting'>;
}
declare module 'react-dom/lib/ViewportMetrics.js' {
  declare module.exports: $Exports<'react-dom/lib/ViewportMetrics'>;
}
declare module 'react-dom/server.js' {
  declare module.exports: $Exports<'react-dom/server'>;
}
declare module 'react-dom/test-utils.js' {
  declare module.exports: $Exports<'react-dom/test-utils'>;
}
