// flow-typed signature: cce74616e4b8e05bd760bde0ff5f5146
// flow-typed version: <<STUB>>/react-html-attributes_v^1.3.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-html-attributes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-html-attributes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-html-attributes/dist/index' {
  declare module.exports: any;
}

declare module 'react-html-attributes/dist/index.umd' {
  declare module.exports: any;
}

declare module 'react-html-attributes/dist/index.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-html-attributes/dist/index.js' {
  declare module.exports: $Exports<'react-html-attributes/dist/index'>;
}
declare module 'react-html-attributes/dist/index.umd.js' {
  declare module.exports: $Exports<'react-html-attributes/dist/index.umd'>;
}
declare module 'react-html-attributes/dist/index.umd.min.js' {
  declare module.exports: $Exports<'react-html-attributes/dist/index.umd.min'>;
}
