// flow-typed signature: d108063164600dddc36a14ed8ded16e4
// flow-typed version: <<STUB>>/svg-elements_v^1.0.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-elements' {
  declare module.exports: any;
}
